package com.adups.distancedays.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "event".
 */
@Entity(nameInDb = "event")
public class EventEntity {

    @Id
    private Long id;
    private String eventContent;
    private Long createDate;
    private Long targetDate;
    private Boolean isLunarCalendar;
    private Boolean top;
    private Integer repeatType;

    @Generated(hash = 893269617)
    public EventEntity() {
    }

    public EventEntity(Long id) {
        this.id = id;
    }

    @Generated(hash = 618707227)
    public EventEntity(Long id, String eventContent, Long createDate, Long targetDate, Boolean isLunarCalendar, Boolean top, Integer repeatType) {
        this.id = id;
        this.eventContent = eventContent;
        this.createDate = createDate;
        this.targetDate = targetDate;
        this.isLunarCalendar = isLunarCalendar;
        this.top = top;
        this.repeatType = repeatType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventContent() {
        return eventContent;
    }

    public void setEventContent(String eventContent) {
        this.eventContent = eventContent;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public Long getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(Long targetDate) {
        this.targetDate = targetDate;
    }

    public Boolean getIsLunarCalendar() {
        return isLunarCalendar;
    }

    public void setIsLunarCalendar(Boolean isLunarCalendar) {
        this.isLunarCalendar = isLunarCalendar;
    }

    public Boolean getTop() {
        return top;
    }

    public void setTop(Boolean top) {
        this.top = top;
    }

    public Integer getRepeatType() {
        return repeatType;
    }

    public void setRepeatType(Integer repeatType) {
        this.repeatType = repeatType;
    }

}
