package com.adups.distancedays.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "event".
 */
@Entity(nameInDb = "event")
public class EventEntity {

    @Id
    private Long id;
    private String eventTitle;
    private Long createDate;
    private Long targetDate;
    private Boolean isLunarCalendar;
    private Boolean isTop;
    private Integer repeatType;

    @Generated(hash = 893269617)
    public EventEntity() {
    }

    public EventEntity(Long id) {
        this.id = id;
    }

    @Generated(hash = 1143467143)
    public EventEntity(Long id, String eventTitle, Long createDate, Long targetDate, Boolean isLunarCalendar, Boolean isTop, Integer repeatType) {
        this.id = id;
        this.eventTitle = eventTitle;
        this.createDate = createDate;
        this.targetDate = targetDate;
        this.isLunarCalendar = isLunarCalendar;
        this.isTop = isTop;
        this.repeatType = repeatType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventTitle() {
        return eventTitle;
    }

    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public Long getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(Long targetDate) {
        this.targetDate = targetDate;
    }

    public Boolean getIsLunarCalendar() {
        return isLunarCalendar;
    }

    public void setIsLunarCalendar(Boolean isLunarCalendar) {
        this.isLunarCalendar = isLunarCalendar;
    }

    public Boolean getIsTop() {
        return isTop;
    }

    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    public Integer getRepeatType() {
        return repeatType;
    }

    public void setRepeatType(Integer repeatType) {
        this.repeatType = repeatType;
    }

}
