package com.adups.distancedays.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "event".
 */
@Entity(nameInDb = "event")
public class EventEntity {

    @Id
    private Long id;
    private String eventContent;
    private Long createDate;
    private Long targetDate;

    @Generated(hash = 893269617)
    public EventEntity() {
    }

    public EventEntity(Long id) {
        this.id = id;
    }

    @Generated(hash = 1293243244)
    public EventEntity(Long id, String eventContent, Long createDate, Long targetDate) {
        this.id = id;
        this.eventContent = eventContent;
        this.createDate = createDate;
        this.targetDate = targetDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventContent() {
        return eventContent;
    }

    public void setEventContent(String eventContent) {
        this.eventContent = eventContent;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public Long getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(Long targetDate) {
        this.targetDate = targetDate;
    }

}
